[package]
name = "timers"
version = "0.1.0"
authors = ["Francesco Pasa <francescopasa@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^2.33.0"
dirs = "^2.0.2"
chrono = "^0.4.10"
colored = "1.9"

[dependencies.rusqlite]
version = "^0.21.0"
features = ["bundled"]